/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include <check.h>

#include "parser.h"

START_TEST(test_open_file_1)
{

const char *inputStr = "objects/Lion.obj";
Parser(inputStr);


}
END_TEST

START_TEST(test_open_file_2)
{

const char *inputStr = "kion.obj";
Parser(inputStr);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_open_file_1);
    tcase_add_test(tc1_1, test_open_file_2);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
